/*
 * WARNING: this is an autogenerated file and will be overwritten by
 * the extension interface script.
 */
#ifndef S3EUNIVERSALLINKS_AUTODEFS_H
#define S3EUNIVERSALLINKS_AUTODEFS_H

/**
 * string name used to locate this extension
 */
#define S3E_EXT_UNIVERSALLINKS_NAME "s3eUniversalLinks"
#define S3E_EXT_UNIVERSALLINKS_HASH 0xcc622eca

#ifdef S3E_EXT_REGISTER
#ifndef S3E_EXT_REGISTER_KEY
#define S3E_EXT_REGISTER_KEY(name, num, key) S3E_EXT_REGISTER(name, num)
#endif
S3E_EXT_REGISTER("s3eUniversalLinks", 3)
#else

#endif /* S3E_EXT_REGISTER */
#endif /* !S3EUNIVERSALLINKS_AUTODEFS_H */
