/*
 * WARNING: this is an autogenerated file and will be overwritten by
 * the extension interface script.
 */
/**
 * Definitions for functions types passed to/from s3eExt interface
 */
typedef  s3eResult(*s3eUniversalLinksTest_t)(const char* str);

/**
 * struct that gets filled in by s3eUniversalLinksRegister
 */
typedef struct s3eUniversalLinksFuncs
{
    s3eUniversalLinksTest_t m_s3eUniversalLinksTest;
} s3eUniversalLinksFuncs;
